FROM lasote/conangcc54

WORKDIR /tmp

ADD bootstrap.sh .
RUN ./bootstrap.sh

ADD conanfile.py .
RUN mkdir build/ && cd build/ \
  && conan install .. -s compiler.libcxx=libstdc++11 --build=missing

RUN sudo rm -rf /tmp/*