apiVersion: v1
kind: ConfigMap
metadata:
  name: is-skeletons-grouper-rpc-config
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "id": 0,
      "cameras": {
        "0" : { "vertices": [{"x": 0.31, "y": 0.0}, {"x": 0.78, "y": 1.0}]},
        "1" : { "vertices": [{"x": 0.21, "y": 0.0}, {"x": 0.71, "y": 1.0}]},
        "2" : { "vertices": [{"x": 0.31, "y": 0.0}, {"x": 0.78, "y": 1.0}]},
        "3" : { "vertices": [{"x": 0.16, "y": 0.0}, {"x": 0.68, "y": 1.0}]}
      },
      "referential": 1000,
      "min_error": 50.0,
      "min_score": 0.4,
      "max_distance": 0.9,
      "period_ms": 100,
      "release_samples": 5
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-grouper-rpc"
spec:
  replicas: 20 
  template:
    metadata:
      labels:
        app: is-skeletons-grouper-rpc
    spec:
      containers:
      - name: service 
        image: viros/is-skeletons-grouper:0.0.3
        command: ["./rpc.bin"]
        args: ["/opt/options/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt/options
      volumes:
      - name: options
        configMap:
          name: is-skeletons-grouper-rpc-config
          items:
          - key: config
            path: options.json
